server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        # \u5B9A\u4E49\u4E86\u4E00\u4E2A\u540D\u4E3A"api_route"\u7684\u8DEF\u7531\u89C4\u5219,\u8BE5\u89C4\u5219\u5C06\u5339\u914D\u4EE5"/api/"\u5F00\u5934\u7684\u8DEF\u5F84,\u4F8B\u5982"/api/user",
        # \u5E76\u5C06\u8FD9\u4E9B\u8BF7\u6C42\u8F6C\u53D1\u5230"http://localhost:8123"\u8FD9\u4E2A\u76EE\u6807\u5730\u5740
        - id: jjlapi-interface
          uri: http://62.234.67.99:8123
          predicates:
            - Path=/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    # 设置应用的名称
    name: dubbo-springboot-demo-provider
  # 指定使用 Dubbo 协议，且端口设置为 -1，表示随机分配可用端口
  protocol:
    name: dubbo
    port: 22223
  registry:
    # 配置注册中心为 Nacos，使用的地址是 nacos://localhost:8848
    id: nacos-registry
    address: nacos://localhost:8848?username=nacos&password=nacos